In [2]:
import pandas as pd

# import data files into dataframe

In [3]:
df1=pd.read_csv('l1_all_data.csv')
df1.head()
df2=pd.read_csv('l2_all_data.csv')
df2.head()

,Unnamed: 0,Name,deg,school,work,titles,URL,edu hist,yrs_school,exp hist,dates_work,places_work
0,0,Abdelhamid jnane,"['Doctor of Philosophy (Ph.D.), Clinical Labor...","['Rutgers University', 'The City College of Ne...","['City College, CCNY']",['Research Assistant'],https://www.linkedin.com/in/abdelhamid-jnane-0...,[],"['2011 - 2015', '2006 - 2010']","['Research Assistant @ City College, CCNY']","[""'Sep 2009 - Present · 13 yrs 6 mos'""]",[]
1,1,"Alejandra Castano, PhD","['Doctor of Philosophy - PhD, Chemistry. Conce...","['Stony Brook University', 'Queens College']","['5 yrs 3 mos', 'Full-time', 'Full-time', '6 y...",['Grant Assistant for the STEP Queensborough B...,https://www.linkedin.com/in/alejandra-castano?...,"['Doctor of Philosophy - PhD, Chemistry. Conce...",[],[],"[""'Jul 2022 - Present · 8 mos"", 'Jul 2021 - Ju...","['Melville, New York, United States', 'Melvill..."
2,2,Amarachi ikwuagwu,"['Doctor of Philosophy - PhD, Educational Psyc...","['Northcentral University', 'Keller Graduate S...","['Con Edison', 'Kraft Foods']","['Engineer', 'Engineering Inetrn']",https://www.linkedin.com/in/amarachi-ikwuagwu-...,"['Doctor of Philosophy - PhD, Educational Psyc...","['2017 - 2022', '2008 - 2010', '2004 - 2005']","['Engineer @ Con Edison', 'Engineering Inetrn ...","[""'Jun 2005 - Present · 17 yrs 9 mos"", 'May 20...","[""Tarrytown , NY'""]"
3,3,Benedette Adewale,"['Doctor of Philosophy (Ph.D.), Chemistry', 'M...","['Stony Brook University', 'The City College o...",['State University of New York College at Old ...,"['Lecturer', 'Graduate Research Assistant', 'U...",https://www.linkedin.com/in/benedette-adewale-...,"['Doctor of Philosophy (Ph.D.), Chemistry @ St...",[],[],"[""'Sep 2017 - Present · 5 yrs 6 mos"", 'Aug 201...",['United States']
4,4,Bertholin Pierre,"['Master of Arts in Teaching Science, Biology,...","['Brooklyn College', 'Medgar Evers College, CU...","['Kingsborough Community College', 'Accelerate...",['Supplemental Math Instructor (Teaching pre- ...,https://www.linkedin.com/in/bertholin-pierre-3...,[],[],['Supplemental Math Instructor (Teaching pre- ...,"[""'Sep 2010 - Present · 12 yrs 6 mos"", ""2010 -...",['Kingsborough Community College (CUNY)']

# functions

In [22]:
type(df1['yrs_working'][43])
df1['yrs_working'][43]
df1['yrs_working'][1]

"['Jul 2021 - Present · 1 yr 8 mos', '2015 - May 2019 · 4 yrs 5 mos', 'Apr 2013 - Apr 2015 · 2 yrs 1 mo', 'Greater New York City Area', 'Feb 2008 - Jun 2012 · 4 yrs 5 mos', 'Sep 2010 - Jun 2011 · 10 mos', 'New York, NY']"

In [38]:
def extract_str_info(A):
    A=A[1:-1]
    B=A.split("', '")
    return B

temp=extract_str_info(df1['yrs_working'][43])
temp

["'Aug 2017 - Present · 5 yrs 7 mos", "New York City Metropolitan Area'"]

In [39]:
def has_numbers(inputString):
    return any(char.isdigit() for char in inputString)

def extract_dates(A):
    B=[]
    for i in A:
        if has_numbers(i):
            B.append(i)
    return B

temp2=extract_dates(temp)
temp2

["'Aug 2017 - Present · 5 yrs 7 mos"]

In [40]:
def only_letters(string):
    return all(letter.isalpha() for letter in string)

def extract_places(A,B):
    C=[]
    for i in A:
        if i not in B:
            C.append(i)
    return C
extract_places(temp,temp2)

["New York City Metropolitan Area'"]

# clean the df

In [49]:
df1['yrs_working']=df1['yrs_working'].apply(extract_str_info)
df1

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,index,Unnamed: 0,Name,deg,school,work,titles,URL,edu hist,exp hist,yrs_working,yrs_school_clean
0,0,0,0,0,0,Minerva Francis,"['Doctor of Education - EdD, Health and Behavi...","['Teachers College, Columbia University', 'Bro...","['CUNY Hostos Community College', 'Silberman S...","['Adjunct Assistant Professor', 'Adjunct', 'Pr...",https://www.linkedin.com/in/minerva-francis-9a...,"['Doctor of Education - EdD, Health and Behavi...",['Adjunct Assistant Professor @ CUNY Hostos Co...,"['Jan 2022 - Present · 1 yr 2 mos, May 2019 - ...",['']
1,1,1,1,1,5,Moody Saint Louis,"['gy)\\n"", Post-baccalaureate Premedical Progr...","['The City College of New York', 'The City Col...","['Mobile Health · Full-time', 'The Fortune Soc...","['Data Integration Manager', 'Software Enginee...",https://www.linkedin.com/in/msaintlouis?miniPr...,[],[],"['Jul 2021 - Present · 1 yr 8 mos, 2015 - May ...","['2006 - 2009', '2005 - 2006', '2000 - 2004']"
2,2,2,2,2,10,Gillian (Cain) Walker,"['Master of Engineering (MEng), Civil Engineer...","['The City College of New York', 'The City Col...","['HVEA Engineers', 'Naik Consulting Group, PC'...","['Project Engineer/Resident Engineer', 'Civil ...",https://www.linkedin.com/in/gillian-walker-03a...,"['Master of Engineering (MEng), Civil Engineer...",['Project Engineer/Resident Engineer @ HVEA En...,[''],['']
3,3,3,3,3,21,Reginald Dorcely,"['Doctor of Education - Ed.D., Mathematics Tea...","['Teachers College, Columbia University', 'The...","['CUNY Hostos Community College · Contract', '...",['Instructor and CSTEP Undergraduate Student R...,https://www.linkedin.com/in/reginald-dorcely-7...,"['Doctor of Education - Ed.D., Mathematics Tea...",['Instructor and CSTEP Undergraduate Student R...,"['Aug 2008 - Present · 14 yrs 7 mos, Bronx, Ne...",['']
4,4,4,4,4,32,Clyde Lewis,"['Master of Arts (M.A.), Mathematics', 'Bachel...",['City University of New York-Herbert H. Lehma...,"['BMCC CUNY Start', 'Borough of Manhattan Comm...","['Full Time Core Mathematics Instructor', 'Adj...",https://www.linkedin.com/in/clyde-lewis-7b7175...,"['Master of Arts (M.A.), Mathematics @ City Un...",['Full Time Core Mathematics Instructor @ BMCC...,"['Feb 2014 - Present · 9 yrs 1 mo, Oct 2013 - ...","['2011 - 2013', '2007 - 2009', '2004 - 2006']"
5,5,5,5,5,45,Angela Padilla,"['Master of Science - MS, Physics Teacher Educ...",['The City College of New York'],[''],[''],https://www.linkedin.com/in/angela-padilla-985...,"['Master of Science - MS, Physics Teacher Educ...",[' @ '],[''],['']
6,6,6,6,6,50,Mohammed Uddin,"['Bachelor of Arts - BA, Human Behavior and Sy...","['Baruch College', 'Academy of American Studies']","['New York Edge · Part-time', 'Intergeneration...","['Data Specialist', 'Research Intern', 'Compet...",https://www.linkedin.com/in/mohammeduddin123?m...,"['Bachelor of Arts - BA, Human Behavior and Sy...",['Data Specialist @ New York Edge · Part-time'...,[''],"['Jan 2023 - May 2024', 'Aug 2017 - May 2021',..."
7,7,7,7,7,53,Mohammed Uddin,"['Information Systems and Psychology , Compute...","['Brooklyn College', 'High School of Economics...","['Initiative · Full-time', 'Neo Media World · ...","['Data Engineer', 'Senior Data Analyst', 'Data...",https://www.linkedin.com/in/mohammed-u?miniPro...,[],"['Data Engineer @ Initiative · Full-time', 'Se...","['Mar 2022 - Present · 1 yr, New York, United ...","['2012 - 2018', '2008 - 2012']"
8,8,8,8,8,54,Mohammad Uddin,"['Bachlors in Computer System Technology, Netw...","['CUNY New York City College of Technology', '...","['BYNEX · Full-time', 'The Mark Hotel · Full-t...","['IT Support Specialist', 'IT Specialist', 'AT...",https://www.linkedin.com/in/mohammad-uddin-a60...,"['Bachlors in Computer System Technology, Netw...","['IT Support Specialist @ BYNEX · Full-time', ...","['Dec 2021 - Nov 2022 · 1 yr, Jun 2021 - Dec 2...","['2018 - 2020', '2014 - 2017', '2011 - 2014']"
9,9,9,9,9,55,"Michael Tavarez, Ph.D.","['Doctor of Philosophy (Ph.D.), Plant Sciences...","['The Graduate Center, City University of New ...","['The Graduate Center, City University of New ...","['Research Associate', 'Adjunct Lecturer- Biol...",https://www.linkedin.com/in/michael-tavarez-ph...,"['Doctor of Philosophy (Ph.D.), Plant Sciences...","['Research Associate @ The Graduate Center, Ci...","['Oct 2022 - Present · 5 mos, Feb 2013 - Prese...","['Sep 2017 - Sep 2021', 'Sep 2013 - Sep 2017',..."
10,10,10,10,10,65,Nkem Stanley,[''],"['The City College of New York', 'The City Col...",['City College of New York'],['Associate Director'],https://www.linkedin.com/in/nkem-stanley-83268...,[],['Associate Director @ City College of New York'],[''],['']
11,11,11,11,11,70,"Sha-Ron Pierre, PhD","['PhD, Biology (Molecular, Cellular and Develo...","['Columbia University', 'The Graduate Center, ...",['Independent Consultant'],['Medical Director'],https://www.linkedin.com/in/sha-ron-pierre-phd...,[],['Medical Director @ Independent Consultant'],['Sep 2018 - Jun 2022 · 3 yrs 10 mos'],"['2008 - 2010', '2003 - 2008', '2001 - 2003']"
12,12,12,12,12,78,Jonathan B.,"['🎓Doctor of Philosophy (Ph.D.), Neuroscience'...","['The Graduate Center, City University of New ...","['PTC Therapeutics, Inc. · Full-time', 'Simple...","['Medical Science Liaison', 'Founder/Lead Scie...",https://www.linkedin.com/in/jonathanb2020?mini...,"['🎓Doctor of Philosophy (Ph.D.), Neuroscience ...",[],"['Dec 2021 - Present · 1 yr 3 mos, Jupiter, Fl...",['']
13,13,13,13,13,89,Adjiwanou Gbagba,['Earth Systems Science and Environmental Engi...,['The City College of New York'],"['Mercy College', 'CUNY- Hostos Community Coll...","['Assistant Director, NYS- Collegiate Science ...",https://www.linkedin.com/in/adjiwanou-gbagba-6...,['Earth Systems Science and Environmental Engi...,"['Assistant Director, NYS- Collegiate Science ...","['Jan 2016 - Present · 7 yrs 2 mos, Dobbs Ferr...",['2012 - 2015']
14,14,14,14,14,97,"Magalie Bruneus, MD","['Doctor of Medicine (M.D.), Medicine', 'Bache...","['Albert Einstein College of Medicine', 'The C...","['Memorial Sloan Kettering Cancer Center', '9 ...","[' Academic Medicine Hospitalist ', 'Assistant...",https://www.linkedin.com/in/magalie-bruneus-md...,"['Doctor of Medicine (M.D.), Medicine @ Albert...",[],"['Jul 2017 - Present · 5 yrs 8 mos, New York C...",['']
15,15,15,15,15,98,Adashima Oyo,"['Doctor of Philosophy - PhD', 'Master of Publ...","['The Graduate Center, City University of New ...","['1 yr 5 mos', 'New York University', 'City Un...","['Adjunct Faculty', 'Adjunct Faculty', 'HASTAC...",https://www.linkedin.com/in/adashimaoyo?miniPr...,['Doctor of Philosophy - PhD @ The Graduate Ce...,[],"['Feb 2022 - Present · 1 yr 1 mo, Aug 2021 - J...",['']
16,16,16,16,16,100,Tamara L. Battle,"['Doctor of Philosophy - PhD (in progress), En...","['Morgan State University', 'Howard University...",['NOAA: National Oceanic & Atmospheric Adminis...,"['Policy Manager', 'Policy Engineer Scientist'...",https://www.linkedin.com/in/tamara-l-battle-91...,"['Doctor of Philosophy - PhD (in progress), En...",['Policy Manager @ NOAA: National Oceanic & At...,[''],"['Aug 2015 - May 2023', '2005 - 2011', '2000 -..."
17,17,17,17,17,114,Nia René,"['Doctor of Philosophy - PhD, Earth and Enviro...","['The Graduate Center, City University of New ...",['NOAA: National Oceanic & Atmospheric Adminis...,"['Environmental Scientist', 'NOAA CESSRST Ph.D...",https://www.linkedin.com/in/nia-ren%C3%A9-8167...,"['Doctor of Philosophy - PhD, Earth and Enviro...",[],"['Sep 2021 - Present · 1 yr 6 mos, Charleston,...","['2019 - 2023', '2019']"
18,18,18,18,18,118,Andrew Blake,"['Certificate, Web Development', 'Computer Sci...","['Thinkful', 'Hunter College', 'Augsburg Unive...","['Hertz', 'Thinkful', 'Sons Acura']","['Automotive Technician', 'Web Developer (Appr...",https://www.linkedin.com/in/andrew-blake-88b17...,"['Certificate, Web Development @ Thinkful', 'C...","['Automotive Technician @ Hertz', 'Web Develop...","['Oct 2013 - Jul 2019 · 5 yrs 10 mos, Greater ...","['2018 - 2019', '1994 - 1996', '1993 - 1994']"
19,19,19,19,19,140,Françoise S.,"['🎓 Ph.D. Neuroscience - Graduate Center, 2015...",['City University of New York-College of State...,"['Helene Fuld College of Nursing', 'Wagner Col...",['Associate Professor/Biological and Chemistry...,https://www.linkedin.com/in/francoisesidime?mi...,"['🎓 Ph.D. Neuroscience - Graduate Center, 2015...",[],"['Nov 2018 - Present · 4 yrs 4 mos, Nov 2018 -...",['']
20,20,20,20,20,160,Jason Mighty,"['Doctor of Philosophy - PhD, Molecular Biolog...","['The Graduate Center, City University of New ...","['3 yrs 6 mos', 'Full-time', 'Simon-Kucher & P...","['Research Assistant', 'Adjunct Lecturer', 'Ad...",https://www.linkedin.com/in/jason-mighty-0b560...,"['Doctor of Philosophy - PhD, Molecular Biolog...",[],"['Jan 2022 - Present · 1 yr 2 mos, Tarrytown, ...",['2013 - 2019']
21,21,21,21,21,165,"Jodi-Ann Young, MSc., ACSM","['Bachelors, Computer Engineering', 'Master of...","['City University of New York City College', '...","['7 yrs 3 mos', 'Full-time', '15 yrs 5 mos', '...",['iOS Certified Technician'],https://www.linkedin.com/in/jodiannyoung?miniP...,"['Bachelors, Computer Engineering @ City Unive...",[],"['Dec 2021 - Present · 1 yr 3 mos, New York Ci...",['']
22,22,22,22,22,170,"Jenny Paredes, PhD","['Doctor of Philosophy - PhD, Cell/Cellular an...","['Downstate Health Sciences University', 'Ston...",['Memorial Sloan Kettering Cancer Center · Ful...,"['Postdoctoral Researcher', 'Researcher Phd Ca...",https://www.linkedin.com/in/jennyparedes01?min...,"['Doctor of Philosophy - PhD, Cell/Cellular an...",[],"['Nov 2020 - Present · 2 yrs 4 mos, New York, ...","['2015 - 2020', '2017 - 2018', '2013 - 2015']"
23,23,23,23,23,175,Professor Rasheem Northington,"['Master of Arts - MA, Adolescent Education in...","['Hunter College', 'Hunter College']",['Eastern International College'],['Professor'],https://www.linkedin.com/in/professor-rasheem-...,"['Master of Arts - MA, Adolescent Education in...",['Professor @ Eastern International College'],['Jan 2022 - Present · 1 yr 2 mos'],"['2005 - 2007', '1996 - 2004']"
24,24,24,24,24,193,"Ivan Baez, P.E.","['BCE, ME, Civil Engineering (Transportation)'...","['The City College of New York', 'The City Col...","['KS Engineers, P.C.', 'CV Associates', 'B&H E...","['Bridge Inspector / Assistan Team Leader', 'A...",https://www.linkedin.com/in/ibaez?miniProfileU...,"['BCE, ME, Civil Engineering (Transportation) ...",[],"['Mar 2016 - Present · 7 yrs, Greater New York...","['1995 - 2002', '1995 - 2002']"
25,25,25,25,25,197,JoAnn Caban,"['Master of Education (M.Ed.), Science Teacher...",['City University of New York- The City Colleg...,['University Prep Charter Highschool · Contrac...,['Permanent Substitute Chemistry Foundations T...,https://www.linkedin.com/in/joanncaban?miniPro...,"['Master of Education (M.Ed.), Science Teacher...",['Permanent Substitute Chemistry Foundations T...,"['Jan 2012 - Present · 11 yrs 2 mos, Departmen...",['2009 - 2011']
26,26,26,26,26,202,Natalie Dastas,"['Phd Candidate, Geological and Earth Sciences...","['The Graduate Center, City University of New ...","['Brooklyn College', 'NYC Louis Stokes Allianc...","['Adjunct Instructor', 'Activity Coordinator']",https://www.linkedin.com/in/natalie-dastas-680...,"['Phd Candidate, Geological and Earth Sciences...","['Adjunct Instructor @ Brooklyn College', 'Act...","['Jan 2012 - Present · 11 yrs 2 mos, Brooklyn,...","['Jan 2010 - Jun 2013', 'Jun 2005 - Feb 2010']"
27,27,27,27,27,203,Juliet Baidoo,"['Doctor of Philosophy (Ph.D.), Biochemistry',...","['The Graduate Center, City University of New ...","['The Graduate Center, City University of New ...","['PhD Candidate', 'Research Assistant', 'Resea...",https://www.linkedin.com/in/juliet-baidoo-3853...,"['Doctor of Philosophy (Ph.D.), Biochemistry @...","['PhD Candidate @ The Graduate Center, City Un...","['Aug 2015 - Present · 7 yrs 7 mos, New York, ...","['2015 - 2021', '2011 - 2015']"
28,28,28,28,28,217,Dr. Carol Woodburn McDonald,"['Doctor of Philosophy (PhD), Urban Education ...","['The Graduate Center, City University of New ...","['Rockdale County High School', 'Northeastern ...","['Teacher', 'Teacher', 'Adjunct Professor']",https://www.linkedin.com/in/dr-carol-woodburn-...,"['Doctor of Philosophy (PhD), Urban Education ...","['Teacher @ Rockdale County High School', 'Tea...","['Jul 2015 - Present · 7 yrs 8 mos, Sep 2007 -...","['2005 - 2009', '2002 - 2004', '1999 - 2002']"
29,29,29,29,29,229,"Uchenna Unachukwu, Ph.D","['Doctor of Philosophy - PhD, Biochemistry', '...","['The Graduate Center, City University of New ...","['Full-time · 7 yrs 4 mos', 'The City Universi...","['Adjunct Assistant Professor, Department of S...",https://www.linkedin.com/in/johnuchenna?miniPr...,"['Doctor of Philosophy - PhD, Biochemistry @ T...",[],"['Sep 2018 - Present · 4 yrs 6 mos, New York, ...",['2009 - 2014']
30,30,30,30,30,245,Vadim Acosta,"['M.A., Environmental Science', '""\\nBachelor\...","['Queens College', 'Queens College']","['Fullstack Academy · Full-time', 'Full-time ·...","['Instructor', 'Adjunct Lecturer', 'Data Analy...",https://www.linkedin.com/in/vadim-acosta?miniP...,"['M.A., Environmental Science @ Queens College...",[],[''],"['2009 - 2012', '2002 - 2009']"
31,31,31,31,31,253,Diomaris Padilla,"['PhD, Earth and Environmental Sciences', 'Mas...","['The Graduate Center, City University of New ...","['New York Institute of Technology', '15 yrs',...","['Lecturer In Physics', 'Scientific Researcher...",https://www.linkedin.com/in/diomaris-padilla-0...,"['PhD, Earth and Environmental Sciences @ The ...",[],[''],"['2001 - 2008', '2001 - 2008', '1992 - 1997']"
32,32,32,32,32,264,Nadine Bennett,[''],['The City College of New York'],['GLY Religious store'],['Academic Advisor'],https://www.linkedin.com/in/nadine-bennett-7b2...,[' @ The City College of New York'],['Academic Advisor @ GLY Religious store'],[''],['2006 - 2009']
33,33,33,33,33,271,Rita Barley,"['Master of Arts (M.A.), Geology/Earth Science...","['The City College of New York', 'Medgar Evers...",[''],[''],https://www.linkedin.com/in/rita-barley-566199...,"['Master of Arts (M.A.), Geology/Earth Science...",[' @ '],[''],"['2008 - 2013', '2002 - 2006']"
34,34,34,34,34,276,Onyekwere O.,[''],['City University of New York- Graduate Center...,['City University of New York-Herbert H. Lehma...,"['Postdoctoral Scientist', 'Adjunct Faculty', ...",https://www.linkedin.com/in/onyekwere-o-122a17...,[],['Postdoctoral Scientist @ City University of ...,"['Jan 2022 - Present · 1 yr 2 mos, Jan 2015 - ...",['']
35,35,35,35,35,278,Sharon Lall-Ramnarine,"['Doctor of Philosophy (Ph.D.), Analytical Che...","['The Graduate Center, City University of New ...","['Full-time · 2 yrs', 'Brookhaven National Lab...","['Research Collaborator and Guest Scientist', ...",https://www.linkedin.com/in/sharon-lall-ramnar...,[],[],"['New York, United States, Jan 2021 - Present ...","['1998 - 2003', '1998 - 2000', '1996 - 1998']"
36,36,36,36,36,293,Jean-Marc Carre,"['Master of Science (M.Sc.), Mechanical Engine...","['The City College of New York', 'City College...","['3 yrs 9 mos', 'Full-time', 'Full-time', '16 ...","['Combustion Turbine Parts Repair Engineer', '...",https://www.linkedin.com/in/jean-marc-carre-31...,"['Master of Science (M.Sc.), Mechanical Engine...",[],"['Oct 2021 - Present · 1 yr 5 mos, Atlanta, Ge...","['2002 - 2003', '1996 - 2001', '1987 - 1991']"
37,37,37,37,37,298,"Mariya Alexandra Mayer, MSPAS, PA-C","['tor of Philosophy - PhD, Health SciencesDoct...","['Stony Brook University', 'University of Sout...","['Griffin Hospital · Full-time', 'New York Bar...","['Surgical Physician Assistant', 'Surgical Phy...",https://www.linkedin.com/in/mariyamayer?miniPr...,[],['Surgical Physician Assistant @ Griffin Hospi...,"['Aug 2022 - Present · 7 mos, United States, A...","['2019 - 2021', '2021 - Jan 2025', '2014 - 2018']"
38,38,38,38,38,302,Marvin Bennett,['Bachelors of Arts/ Master of Science (B.A./M...,['City University of New York-Herbert H. Lehma...,"['Yale University', 'New York City College of ...","['Graduate Student', 'Activity Coordinator, LS...",https://www.linkedin.com/in/marvin-bennett-134...,['Bachelors of Arts/ Master of Science (B.A./M...,[],"['Aug 2017 - Present · 5 yrs 7 mos, Sep 2014 -...","['2009 - 2015', '2003 - 2008']"
39,39,39,39,39,306,Giselle Acco,"['Master, chemical engineer']",['The City College of New York'],['City University of New York - Borough of man...,"['Activity Coordinator', 'Chemical Engineer In...",https://www.linkedin.com/in/giselle-acco-ba0a5...,"['Master, chemical engineer @ The City College...",['Activity Coordinator @ City University of Ne...,"['Aug 2007 - Present · 15 yrs 7 mos, Jun 2005 ...",['2007 - 2009']
40,40,40,40,0,0,Lori Collins,[''],[''],"['US Army Futures Command, CCDC · Full-time']",['Computer Engineer'],https://www.linkedin.com/in/lori-collins-a6411...,[' @ '],"['Computer Engineer @ US Army Futures Command,...",['Jan 2008 - Present · 15 yrs 2 mos'],['']
41,41,41,41,1,1,Vaughn-Clai Marsh,"['Juris Doctor, Law', 'Masters, Chemical Engin...","['New England Law | Boston', 'The City College...",['Bryan Cave Leighton Paisner LLP · Full-time'...,"['Compliance and Conflicts Attorney', 'Senior ...",https://www.linkedin.com/in/vaughn-clai-marsh-...,"['Juris Doctor, Law @ New England Law | Boston...",['Compliance and Conflicts Attorney @ Bryan Ca...,"['May 2021 - Present · 1 yr 10 mos, Phoenix, A...","['2007 - 2010', '2004 - 2006', '1999 - 2003']"
42,42,42,42,2,2,Allie O.,[''],[''],[''],[''],https://www.linkedin.com/in/allieorellana,[' @ '],[' @ '],[''],['']
43,43,43,43,3,3,Ana Alas Iglesias,"['Master of Arts (M.A.), Economics', 'Bachelor...","['The New School', 'Baruch College', 'Borough ...",['Baruch College · Full-time'],['Sponsored Programs Coordinator'],https://www.linkedin.com/in/aalasiglesias,"['Master of Arts (M.A.), Economics @ The New S...",['Sponsored Programs Coordinator @ Baruch Coll...,"['Aug 2017 - Present · 5 yrs 7 mos, New York C...","['2016 - 2018', 'Jan 2013 - May 2016', '2011 -..."
44,44,44,44,4,4,Angela Padilla,"['Master of Science - MS, Physics Teacher Educ...",['The City College of New York'],[''],[''],https://www.linkedin.com/in/angela-padilla-985...,"['Master of Science - MS, Physics Teacher Educ...",[' @ '],[''],['2016 - 2023']
45,45,45,45,5,5,"Dorean Flores, MPA, CIP",[''],[''],[''],[''],https://www.linkedin.com/in/doreanflores,[' @ '],[' @ '],[''],['']
46,46,46,46,6,6,Anthony Cruz-Balberdy,"['Doctor of Philosophy (Ph.D.), Chemistry - Mo...","['The Graduate Center, City University of New ...","['Ventus Therapeutics · Full-time', 'OpenEye S...","['Senior Scientist', 'Summer Intern', 'Summer ...",https://www.linkedin.com/in/anthony-cruz-balbe...,"['Doctor of Philosophy (Ph.D.), Chemistry - Mo...",['Senior Scientist @ Ventus Therapeutics · Ful...,"['May 2021 - Present · 1 yr 10 mos, Waltham, M...",['']
47,47,47,47,7,7,Andrew Wills,"['Bachelor’s Degree, Applied Mathematics', 'As...","['CUNY New York City College of Technology', '...","['Brooklyn Public Library', 'Safe In My Brothe...","['Consultant', 'Tutor', 'Treasurer', 'Research...",https://www.linkedin.com/in/andrew-wills-67a1a289,"['Bachelor’s Degree, Applied Mathematics @ CUN...","['Consultant @ Brooklyn Public Library', 'Tuto...","['Jan 2016 - Present · 7 yrs 2 mos, Dec 2015 -...",['']

In [53]:
df1['dates_work']=df1['yrs_working'].apply(extract_dates)
# df1['places_work']=df1[['yrs_working','dates_work']].apply(extract_places)

df1['places_work'] = df1.apply(lambda x: extract_places(x.yrs_working, x.dates_work), axis=1)
df1=df1[['Name', 'deg', 'school', 'work', 'titles', 'URL', 'edu hist','yrs_school_clean',
       'exp hist','dates_work','places_work']]
df1.head()

,Name,deg,school,work,titles,URL,edu hist,yrs_school_clean,exp hist,dates_work,places_work
0,Minerva Francis,"['Doctor of Education - EdD, Health and Behavi...","['Teachers College, Columbia University', 'Bro...","['CUNY Hostos Community College', 'Silberman S...","['Adjunct Assistant Professor', 'Adjunct', 'Pr...",https://www.linkedin.com/in/minerva-francis-9a...,"['Doctor of Education - EdD, Health and Behavi...",[''],['Adjunct Assistant Professor @ CUNY Hostos Co...,"['Jan 2022 - Present · 1 yr 2 mos, May 2019 - ...",[]
1,Moody Saint Louis,"['gy)\\n"", Post-baccalaureate Premedical Progr...","['The City College of New York', 'The City Col...","['Mobile Health · Full-time', 'The Fortune Soc...","['Data Integration Manager', 'Software Enginee...",https://www.linkedin.com/in/msaintlouis?miniPr...,[],"['2006 - 2009', '2005 - 2006', '2000 - 2004']",[],"['Jul 2021 - Present · 1 yr 8 mos, 2015 - May ...","[Greater New York City Area, New York, NY']"
2,Gillian (Cain) Walker,"['Master of Engineering (MEng), Civil Engineer...","['The City College of New York', 'The City Col...","['HVEA Engineers', 'Naik Consulting Group, PC'...","['Project Engineer/Resident Engineer', 'Civil ...",https://www.linkedin.com/in/gillian-walker-03a...,"['Master of Engineering (MEng), Civil Engineer...",[''],['Project Engineer/Resident Engineer @ HVEA En...,[],['']
3,Reginald Dorcely,"['Doctor of Education - Ed.D., Mathematics Tea...","['Teachers College, Columbia University', 'The...","['CUNY Hostos Community College · Contract', '...",['Instructor and CSTEP Undergraduate Student R...,https://www.linkedin.com/in/reginald-dorcely-7...,"['Doctor of Education - Ed.D., Mathematics Tea...",[''],['Instructor and CSTEP Undergraduate Student R...,"['Aug 2008 - Present · 14 yrs 7 mos, Aug 2018 ...","[Bronx, New York, United States, New York City..."
4,Clyde Lewis,"['Master of Arts (M.A.), Mathematics', 'Bachel...",['City University of New York-Herbert H. Lehma...,"['BMCC CUNY Start', 'Borough of Manhattan Comm...","['Full Time Core Mathematics Instructor', 'Adj...",https://www.linkedin.com/in/clyde-lewis-7b7175...,"['Master of Arts (M.A.), Mathematics @ City Un...","['2011 - 2013', '2007 - 2009', '2004 - 2006']",['Full Time Core Mathematics Instructor @ BMCC...,"['Feb 2014 - Present · 9 yrs 1 mo, Oct 2013 - ...",[]

In [54]:
df1.to_csv('l1_all_data.csv')

In [60]:
df2['yrs_working']=df2['yrs_working'].apply(extract_str_info)
df2.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Name,deg,school,work,titles,URL,edu hist,exp hist,yrs_working,yrs_school
0,0,0,0,Abdelhamid jnane,"['Doctor of Philosophy (Ph.D.), Clinical Labor...","['Rutgers University', 'The City College of Ne...","['City College, CCNY']",['Research Assistant'],https://www.linkedin.com/in/abdelhamid-jnane-0...,[],"['Research Assistant @ City College, CCNY']",['Sep 2009 - Present · 13 yrs 6 mos'],"['2011 - 2015', '2006 - 2010']"
1,1,1,7,"Alejandra Castano, PhD","['Doctor of Philosophy - PhD, Chemistry. Conce...","['Stony Brook University', 'Queens College']","['5 yrs 3 mos', 'Full-time', 'Full-time', '6 y...",['Grant Assistant for the STEP Queensborough B...,https://www.linkedin.com/in/alejandra-castano?...,"['Doctor of Philosophy - PhD, Chemistry. Conce...",[],"['Jul 2022 - Present · 8 mos, Melville, New Yo...",[]
2,2,2,16,Amarachi ikwuagwu,"['Doctor of Philosophy - PhD, Educational Psyc...","['Northcentral University', 'Keller Graduate S...","['Con Edison', 'Kraft Foods']","['Engineer', 'Engineering Inetrn']",https://www.linkedin.com/in/amarachi-ikwuagwu-...,"['Doctor of Philosophy - PhD, Educational Psyc...","['Engineer @ Con Edison', 'Engineering Inetrn ...","['Jun 2005 - Present · 17 yrs 9 mos, May 2002 ...","['2017 - 2022', '2008 - 2010', '2004 - 2005']"
3,3,3,36,Benedette Adewale,"['Doctor of Philosophy (Ph.D.), Chemistry', 'M...","['Stony Brook University', 'The City College o...",['State University of New York College at Old ...,"['Lecturer', 'Graduate Research Assistant', 'U...",https://www.linkedin.com/in/benedette-adewale-...,"['Doctor of Philosophy (Ph.D.), Chemistry @ St...",[],"['Sep 2017 - Present · 5 yrs 6 mos, Aug 2011 -...",[]
4,4,4,37,Bertholin Pierre,"['Master of Arts in Teaching Science, Biology,...","['Brooklyn College', 'Medgar Evers College, CU...","['Kingsborough Community College', 'Accelerate...",['Supplemental Math Instructor (Teaching pre- ...,https://www.linkedin.com/in/bertholin-pierre-3...,[],['Supplemental Math Instructor (Teaching pre- ...,"['Sep 2010 - Present · 12 yrs 6 mos, Kingsboro...",[]

In [63]:
df2['yrs_working'][1]

["'Jul 2022 - Present · 8 mos",
 'Melville, New York, United States',
 'Jul 2021 - Jul 2022 · 1 yr 1 mo',
 'Melville, New York, United States',
 'Jul 2019 - Jul 2021 · 2 yrs 1 mo',
 'Melville, New York',
 'Stony Brook, NY',
 'Aug 2010 - Jun 2017 · 6 yrs 11 mos',
 'Aug 2012 - Dec 2013 · 1 yr 5 mos',
 'Jul 2008 - Aug 2012 · 4 yrs 2 mos',
 'Queens College',
 'Jun 2006 - Jul 2009 · 3 yrs 2 mos',
 "Upton, NY'"]

In [68]:
df2['dates_work']=df2['yrs_working'].apply(extract_dates)

df2['places_work'] = df2.apply(lambda x: extract_places(x.yrs_working, x.dates_work), axis=1)
df2=df2[['Name', 'deg', 'school', 'work', 'titles', 'URL', 'edu hist','yrs_school',
        'exp hist','dates_work','places_work']]
df2.head()

,Name,deg,school,work,titles,URL,edu hist,yrs_school,exp hist,dates_work,places_work
0,Abdelhamid jnane,"['Doctor of Philosophy (Ph.D.), Clinical Labor...","['Rutgers University', 'The City College of Ne...","['City College, CCNY']",['Research Assistant'],https://www.linkedin.com/in/abdelhamid-jnane-0...,[],"['2011 - 2015', '2006 - 2010']","['Research Assistant @ City College, CCNY']",['Sep 2009 - Present · 13 yrs 6 mos'],[]
1,"Alejandra Castano, PhD","['Doctor of Philosophy - PhD, Chemistry. Conce...","['Stony Brook University', 'Queens College']","['5 yrs 3 mos', 'Full-time', 'Full-time', '6 y...",['Grant Assistant for the STEP Queensborough B...,https://www.linkedin.com/in/alejandra-castano?...,"['Doctor of Philosophy - PhD, Chemistry. Conce...",[],[],"['Jul 2022 - Present · 8 mos, Jul 2021 - Jul 2...","[Melville, New York, United States, Melville, ..."
2,Amarachi ikwuagwu,"['Doctor of Philosophy - PhD, Educational Psyc...","['Northcentral University', 'Keller Graduate S...","['Con Edison', 'Kraft Foods']","['Engineer', 'Engineering Inetrn']",https://www.linkedin.com/in/amarachi-ikwuagwu-...,"['Doctor of Philosophy - PhD, Educational Psyc...","['2017 - 2022', '2008 - 2010', '2004 - 2005']","['Engineer @ Con Edison', 'Engineering Inetrn ...","['Jun 2005 - Present · 17 yrs 9 mos, May 2002 ...","[Tarrytown , NY']"
3,Benedette Adewale,"['Doctor of Philosophy (Ph.D.), Chemistry', 'M...","['Stony Brook University', 'The City College o...",['State University of New York College at Old ...,"['Lecturer', 'Graduate Research Assistant', 'U...",https://www.linkedin.com/in/benedette-adewale-...,"['Doctor of Philosophy (Ph.D.), Chemistry @ St...",[],[],"['Sep 2017 - Present · 5 yrs 6 mos, Aug 2011 -...",[United States]
4,Bertholin Pierre,"['Master of Arts in Teaching Science, Biology,...","['Brooklyn College', 'Medgar Evers College, CU...","['Kingsborough Community College', 'Accelerate...",['Supplemental Math Instructor (Teaching pre- ...,https://www.linkedin.com/in/bertholin-pierre-3...,[],[],['Supplemental Math Instructor (Teaching pre- ...,"['Sep 2010 - Present · 12 yrs 6 mos, 2010 - Pr...",[Kingsborough Community College (CUNY)]

In [69]:
df2.to_csv('l2_all_data.csv')

# school location db

In [13]:
df_cc=pd.read_csv("cc_download.csv")
df_cc=df_cc[['name','city','state']]
df_cc

'Columbia University in the City of New York' in list(df_cc['name'])
# a=df_cc['state'][df_cc['name']=='Aaniiih Nakoda College']
# aa=[]
# aa.append(a)
# aa

True

In [99]:
df_cc

                                         name        city state
0     A T Still University of Health Sciences  Kirksville    MO
1                      Aaniiih Nakoda College      Harlem    MT
2                Abilene Christian University     Abilene    TX
3        Abraham Baldwin Agricultural College      Tifton    GA
4                  Abraham Lincoln University    Glendale    CA
...                                       ...         ...   ...
3934              Youngstown State University  Youngstown    OH
3935             YTI Career Institute-Altoona     Altoona    PA
3936                YTI Career Institute-York        York    PA
3937                             Yuba College  Marysville    CA
3938                       Zane State College  Zanesville    OH

[3939 rows x 3 columns]

In [85]:
df2['school'][1]

"['Stony Brook University', 'Queens College']"

In [86]:
def clean_schools(A):
    A=A[1:-1]
    A=A.split("', '")
    if len(A)!=0:
        A[0]=A[0].replace("'","")
        A[-1]=A[-1].replace("'","")
    return A
clean_schools(df2['school'][1])

['Stony Brook University', 'Queens College']

In [90]:
df2['school']=df2['school'].apply(clean_schools)

,Unnamed: 0,Name,deg,school,work,titles,URL,edu hist,yrs_school,exp hist,dates_work,places_work
0,0,Abdelhamid jnane,"['Doctor of Philosophy (Ph.D.), Clinical Labor...","[Rutgers University, The City College of New Y...","['City College, CCNY']",['Research Assistant'],https://www.linkedin.com/in/abdelhamid-jnane-0...,[],"['2011 - 2015', '2006 - 2010']","['Research Assistant @ City College, CCNY']","[""'Sep 2009 - Present · 13 yrs 6 mos'""]",[]
1,1,"Alejandra Castano, PhD","['Doctor of Philosophy - PhD, Chemistry. Conce...","[Stony Brook University, Queens College]","['5 yrs 3 mos', 'Full-time', 'Full-time', '6 y...",['Grant Assistant for the STEP Queensborough B...,https://www.linkedin.com/in/alejandra-castano?...,"['Doctor of Philosophy - PhD, Chemistry. Conce...",[],[],"[""'Jul 2022 - Present · 8 mos"", 'Jul 2021 - Ju...","['Melville, New York, United States', 'Melvill..."
2,2,Amarachi ikwuagwu,"['Doctor of Philosophy - PhD, Educational Psyc...","[Northcentral University, Keller Graduate Scho...","['Con Edison', 'Kraft Foods']","['Engineer', 'Engineering Inetrn']",https://www.linkedin.com/in/amarachi-ikwuagwu-...,"['Doctor of Philosophy - PhD, Educational Psyc...","['2017 - 2022', '2008 - 2010', '2004 - 2005']","['Engineer @ Con Edison', 'Engineering Inetrn ...","[""'Jun 2005 - Present · 17 yrs 9 mos"", 'May 20...","[""Tarrytown , NY'""]"
3,3,Benedette Adewale,"['Doctor of Philosophy (Ph.D.), Chemistry', 'M...","[Stony Brook University, The City College of N...",['State University of New York College at Old ...,"['Lecturer', 'Graduate Research Assistant', 'U...",https://www.linkedin.com/in/benedette-adewale-...,"['Doctor of Philosophy (Ph.D.), Chemistry @ St...",[],[],"[""'Sep 2017 - Present · 5 yrs 6 mos"", 'Aug 201...",['United States']
4,4,Bertholin Pierre,"['Master of Arts in Teaching Science, Biology,...","[Brooklyn College, Medgar Evers College, CUNY]","['Kingsborough Community College', 'Accelerate...",['Supplemental Math Instructor (Teaching pre- ...,https://www.linkedin.com/in/bertholin-pierre-3...,[],[],['Supplemental Math Instructor (Teaching pre- ...,"[""'Sep 2010 - Present · 12 yrs 6 mos"", ""2010 -...",['Kingsborough Community College (CUNY)']

In [91]:
df1['school']=df1['school'].apply(clean_schools)

In [119]:
df1['school'][2]

['The City College of New York', 'The City College of New York']

In [118]:
def finding_cc_location(A):
    B=[]
    available_school=list(df_cc['name'])
    for i in A:
        if i in available_school:
            j=df_cc['state'][df_cc['name']==i]
            B.append(j)
        else:
            B.append("Not Found")
    return B
finding_cc_location(df1['school'][27])

['Not Found', 'Not Found']

In [32]:
ppl_captured=list(df2['Name'])
ppl_captured

['Abdelhamid jnane',
 'Alejandra Castano, PhD',
 'Amarachi ikwuagwu',
 'Benedette Adewale',
 'Bertholin Pierre',
 'Carlos Jaramillo',
 'Carmen I. Carrión, PsyD',
 'Charlie Corredor',
 'Charren C. Cabaroy',
 'Christian Paylor-Smith',
 'Christian Paylor-Smith',
 'Christina M. Cuttitta',
 'Cliff Bishop',
 'Clyde Lewis',
 'Dana Warmsley, Ph.D.',
 'Evelyn Teran',
 'Fouad Nasraddine',
 'Francis S.',
 'Françoise S.',
 'Grace P. Malonga',
 'Hassan M Oubei',
 'Jason Mighty',
 'Dinely Colon',
 'Elana Cooper',
 'Emmanuel Ekwedike, Ph.D.',
 'Erica F.',
 'Eva Atia',
 'Jean-pierre N Njante',
 'Jesse John, PhD',
 'Jesse St. John',
 'JoAnn Caban',
 'Jose Cortes, MCSD',
 'Jose Perez',
 'Jose Perez',
 'Jose Saltos',
 'Kareem Joshua',
 'Mamadou Moustapha',
 'Maria M.',
 'Mark Carpenay',
 'Mark Carpenay',
 'Michael Tavarez, Ph.D.',
 'Miguel Garcia',
 'Miguel A. Garcia, PhD',
 'Richard Able',
 'Samsiya Ona',
 'Sandra Tinta',
 'Silmilly Toribio Alvarez',
 'Thierno souleymane Diallo',
 'Souleymane Diallo B.S',
 'Thierno Souleymane Diallo',
 'Vadim Acosta',
 'Wahiba Berkane']

In [28]:
df_l2="""Richard Able
Richard Able
Faouzi Abousalham
Vadim Acosta
Benedette Adewale
Benedette Adewale
Eva Atia
Wahiba Berkane
Clifford Bishop 
Jonathan Blaze
Jonathan Blaze
Robert Boria 
Robert Boria 
Pierre Bouzi
Pierre Bouzi
Adina Boyce
Adina Boyce
Luis Bravo
Luis Bravo
Joann Caban
Charren Cabaroy
Angel Calle
Angel Calle
Jonathan Cardenas
Mark Carpenay
Raul Carranza
Carmen Carrion
Carmen Carrion
Alejandra Castano
Alejandra Castano
Jean Cesarius
Jean Cesarius
Lori Collins
Lori Collins
Dinely Colon
Terry Cook
Terry Cook
Elana Cooper
Elana Cooper
Lina Cordero
Charlie Corredor
Charlie Corredor
Jose Cortes
Jose Cortes
Hilda Crispin
Christina Cuttitta
Natalie Dastas
Natalie Dastas
Kiyya Davis
Kiyya Davis
Thierry Desrosiers
Souleymane Diallo
Rachele Dolce Rameau
Rachele Dolce Rameau
Emmanuel Ekwedike
Emmanuel Ekwedike
Amarachukwu Enemuo
Amarachukwu Enemuo
Nicole Febles
Nicole Febles
Erica Fells
Kristina Foulias
Shawndel Fraser
Miguel Garcia
Miguel Garcia
Eugene Gonzalez lopez
Eugene Gonzalez lopez
Olusegun Goyea
Francisco Guzman
Francisco Guzman
Nathan Hosannah
Nathan Hosannah
Amarachi Ikwuagwu
Carlos Jaramillo
Carlos Jaramillo
Nodvige Jean-Louis
Abdelhamid Jnane
Jesse John
Jesse John
Wainwright Joseph
Wainwright Joseph
Mitch Joseph
Kareem Joshua
Tiffany Lambert
Clyde Lewis
Clyde Lewis
Ayemone Likoua
Miguel Lopez
Jonathan Maitre
Grace Malonga
Abdelrahim Mansour
Evlyn Mark
Amora Mayo Perez
Troy McCord
Maria Mercedes
Hans Michell
Jason Mighty
Jason Mighty
Odingo Mitchell
Ayanna Moses
Mamadou Moustapha
Fouad Nasraddine
Clara Nieto-Wire
Clara Nieto-Wire
Jean Pierre Njante
Philipa Njau
Oluwatosin Ogunwuyi
Samsiya Ona
Samsiya Ona
Alicia Orellana
Alicia Orellana
Sandra Ospina
Hassan Oubei
Jamie Parker
Jamie Parker
Christian Paylor Smith
Jorge Peche
Jose Perez
Jose Perez
Herns Pierre
Bertholin Pierre
Leah Pride-Otubanjo
Leah Pride-Otubanjo
Diana Ramroop
Diana Ramroop
Barbara Rizzo
Pedro Rojas
Pedro Rojas
Jennifer Ross
Henry Ruiz
Henry Ruiz
Yisa Rumala
Aminat Saliu
Aminat Saliu
Jose Saltos
Jose Saltos
Eric Sanchez
Eric Sanchez
Katherine Shirley
Francoise Sidime
Francoise Sidime
Carlos Silvera Batista
Carlos Silvera Batista
Francis Smith
Francis Smith
Zoe Spanos
Peter Springer
Josiah Sugarman
Rubens Sylvain
Michael Tavarez
Michael Tavarez
Evelyn Teran
Martino Thenor
Sandra Tinta
Sandra Tinta
Silmilly Toribio
Silmilly Toribio
Amanda Vasquez
Kizzy Vasquez
Rafiah Vitalis
Shari  Walcott
Robin Walker
Dana Warmsley
Dana Warmsley
Ryan Willis
Karla Wyatt
Karla Wyatt
Jumie Yuventi
Jumie Yuventi"""

In [33]:
l2_ppl=set(df_l2.split('\n'))
sorted(l2_ppl)

['Abdelhamid Jnane',
 'Abdelrahim Mansour',
 'Adina Boyce',
 'Alejandra Castano',
 'Alicia Orellana',
 'Amanda Vasquez',
 'Amarachi Ikwuagwu',
 'Amarachukwu Enemuo',
 'Aminat Saliu',
 'Amora Mayo Perez',
 'Angel Calle',
 'Ayanna Moses',
 'Ayemone Likoua',
 'Barbara Rizzo',
 'Benedette Adewale',
 'Bertholin Pierre',
 'Carlos Jaramillo',
 'Carlos Silvera Batista',
 'Carmen Carrion',
 'Charlie Corredor',
 'Charren Cabaroy',
 'Christian Paylor Smith',
 'Christina Cuttitta',
 'Clara Nieto-Wire',
 'Clifford Bishop\xa0',
 'Clyde Lewis',
 'Dana Warmsley',
 'Diana Ramroop',
 'Dinely Colon',
 'Elana Cooper',
 'Emmanuel Ekwedike',
 'Eric Sanchez',
 'Erica Fells',
 'Eugene Gonzalez lopez',
 'Eva Atia',
 'Evelyn Teran',
 'Evlyn Mark',
 'Faouzi Abousalham',
 'Fouad Nasraddine',
 'Francis Smith',
 'Francisco Guzman',
 'Francoise Sidime',
 'Grace Malonga',
 'Hans Michell',
 'Hassan Oubei',
 'Henry Ruiz',
 'Herns Pierre',
 'Hilda Crispin',
 'Jamie Parker',
 'Jason Mighty',
 'Jean Cesarius',
 'Jean Pierre Njante',
 'Jennifer Ross',
 'Jesse John',
 'Joann Caban',
 'Jonathan Blaze',
 'Jonathan Cardenas',
 'Jonathan Maitre',
 'Jorge Peche',
 'Jose Cortes',
 'Jose Perez',
 'Jose Saltos',
 'Josiah Sugarman',
 'Jumie Yuventi',
 'Kareem Joshua',
 'Karla Wyatt',
 'Katherine Shirley',
 'Kiyya Davis',
 'Kizzy Vasquez',
 'Kristina Foulias',
 'Leah Pride-Otubanjo',
 'Lina Cordero',
 'Lori Collins',
 'Luis Bravo',
 'Mamadou Moustapha',
 'Maria Mercedes',
 'Mark Carpenay',
 'Martino Thenor',
 'Michael Tavarez',
 'Miguel Garcia',
 'Miguel Lopez',
 'Mitch Joseph',
 'Natalie Dastas',
 'Nathan Hosannah',
 'Nicole Febles',
 'Nodvige Jean-Louis',
 'Odingo Mitchell',
 'Olusegun Goyea',
 'Oluwatosin Ogunwuyi',
 'Pedro Rojas',
 'Peter Springer',
 'Philipa Njau',
 'Pierre Bouzi',
 'Rachele Dolce Rameau',
 'Rafiah Vitalis',
 'Raul Carranza',
 'Richard Able',
 'Robert Boria\xa0',
 'Robin Walker',
 'Rubens Sylvain',
 'Ryan Willis',
 'Samsiya Ona',
 'Sandra Ospina',
 'Sandra Tinta',
 'Shari\xa0 Walcott',
 'Shawndel Fraser',
 'Silmilly Toribio',
 'Souleymane Diallo',
 'Terry Cook',
 'Thierry Desrosiers',
 'Tiffany Lambert',
 'Troy McCord',
 'Vadim Acosta',
 'Wahiba Berkane',
 'Wainwright Joseph',
 'Yisa Rumala',
 'Zoe Spanos']

In [23]:
names=[]

for i in l2_ppl:
    cur=i.replace(u'\xa0', u' ')
    names.append(cur)
print(sorted(names))

['Abdelhamid Jnane', 'Abdelrahim Mansour', 'Adina Boyce', 'Alejandra Castano', 'Alicia Orellana', 'Amanda Vasquez', 'Amarachi Ikwuagwu', 'Amarachukwu Enemuo', 'Aminat Saliu', 'Amora Mayo Perez', 'Angel Calle', 'Ayanna Moses', 'Ayemone Likoua', 'Barbara Rizzo', 'Benedette Adewale', 'Bertholin Pierre', 'Carlos Jaramillo', 'Carlos Silvera Batista', 'Carmen Carrion', 'Charlie Corredor', 'Charren Cabaroy', 'Christian Paylor Smith', 'Christina Cuttitta', 'Clara Nieto-Wire', 'Clifford Bishop ', 'Clyde Lewis', 'Dana Warmsley', 'Diana Ramroop', 'Dinely Colon', 'Elana Cooper', 'Emmanuel Ekwedike', 'Eric Sanchez', 'Erica Fells', 'Eugene Gonzalez lopez', 'Eva Atia', 'Evelyn Teran', 'Evlyn Mark', 'Faouzi Abousalham', 'Fouad Nasraddine', 'Francis Smith', 'Francisco Guzman', 'Francoise Sidime', 'Grace Malonga', 'Hans Michell', 'Hassan Oubei', 'Henry Ruiz', 'Herns Pierre', 'Hilda Crispin', 'Jamie Parker', 'Jason Mighty', 'Jean Cesarius', 'Jean Pierre Njante', 'Jennifer Ross', 'Jesse John', 'Joann Caban', 'Jonathan Blaze', 'Jonathan Cardenas', 'Jonathan Maitre', 'Jorge Peche', 'Jose Cortes', 'Jose Perez', 'Jose Saltos', 'Josiah Sugarman', 'Jumie Yuventi', 'Kareem Joshua', 'Karla Wyatt', 'Katherine Shirley', 'Kiyya Davis', 'Kizzy Vasquez', 'Kristina Foulias', 'Leah Pride-Otubanjo', 'Lina Cordero', 'Lori Collins', 'Luis Bravo', 'Mamadou Moustapha', 'Maria Mercedes', 'Mark Carpenay', 'Martino Thenor', 'Michael Tavarez', 'Miguel Garcia', 'Miguel Lopez', 'Mitch Joseph', 'Natalie Dastas', 'Nathan Hosannah', 'Nicole Febles', 'Nodvige Jean-Louis', 'Odingo Mitchell', 'Olusegun Goyea', 'Oluwatosin Ogunwuyi', 'Pedro Rojas', 'Peter Springer', 'Philipa Njau', 'Pierre Bouzi', 'Rachele Dolce Rameau', 'Rafiah Vitalis', 'Raul Carranza', 'Richard Able', 'Robert Boria ', 'Robin Walker', 'Rubens Sylvain', 'Ryan Willis', 'Samsiya Ona', 'Sandra Ospina', 'Sandra Tinta', 'Shari  Walcott', 'Shawndel Fraser', 'Silmilly Toribio', 'Souleymane Diallo', 'Terry Cook', 'Thierry Desrosiers', 'Tiffany Lambert', 'Troy McCord', 'Vadim Acosta', 'Wahiba Berkane', 'Wainwright Joseph', 'Yisa Rumala', 'Zoe Spanos']

In [24]:
ppl_not_captured=[]
for i in names:
    if i not in ppl_captured:
        ppl_not_captured.append(i)
print(ppl_not_captured)

['Amarachukwu Enemuo', 'Abdelhamid Jnane', 'Dana Warmsley', 'Shawndel Fraser', 'Souleymane Diallo', 'Rafiah Vitalis', 'Amanda Vasquez', 'Herns Pierre', 'Philipa Njau', 'Zoe Spanos', 'Christian Paylor Smith', 'Luis Bravo', 'Ryan Willis', 'Eric Sanchez', 'Natalie Dastas', 'Olusegun Goyea', 'Tiffany Lambert', 'Jose Cortes', 'Odingo Mitchell', 'Hassan Oubei', 'Angel Calle', 'Wainwright Joseph', 'Miguel Lopez', 'Nicole Febles', 'Francisco Guzman', 'Josiah Sugarman', 'Faouzi Abousalham', 'Jennifer Ross', 'Robert Boria ', 'Troy McCord', 'Kizzy Vasquez', 'Jonathan Cardenas', 'Pierre Bouzi', 'Jesse John', 'Jonathan Blaze', 'Henry Ruiz', 'Aminat Saliu', 'Adina Boyce', 'Jonathan Maitre', 'Lina Cordero', 'Mitch Joseph', 'Abdelrahim Mansour', 'Francoise Sidime', 'Francis Smith', 'Pedro Rojas', 'Terry Cook', 'Silmilly Toribio', 'Leah Pride-Otubanjo', 'Jean Cesarius', 'Grace Malonga', 'Peter Springer', 'Oluwatosin Ogunwuyi', 'Michael Tavarez', 'Christina Cuttitta', 'Evlyn Mark', 'Sandra Ospina', 'Karla Wyatt', 'Jorge Peche', 'Carlos Silvera Batista', 'Kiyya Davis', 'Ayanna Moses', 'Jumie Yuventi', 'Carmen Carrion', 'Yisa Rumala', 'Charren Cabaroy', 'Rachele Dolce Rameau', 'Rubens Sylvain', 'Jamie Parker', 'Shari  Walcott', 'Erica Fells', 'Lori Collins', 'Eugene Gonzalez lopez', 'Katherine Shirley', 'Robin Walker', 'Amora Mayo Perez', 'Diana Ramroop', 'Alicia Orellana', 'Hilda Crispin', 'Martino Thenor', 'Thierry Desrosiers', 'Nathan Hosannah', 'Clara Nieto-Wire', 'Amarachi Ikwuagwu', 'Joann Caban', 'Kristina Foulias', 'Emmanuel Ekwedike', 'Ayemone Likoua', 'Raul Carranza', 'Nodvige Jean-Louis', 'Clifford Bishop ', 'Barbara Rizzo', 'Hans Michell', 'Jean Pierre Njante', 'Maria Mercedes', 'Alejandra Castano']

In [27]:
len(names)

117

In [25]:
ppl_captured

['Abdelhamid jnane',
 'Alejandra Castano, PhD',
 'Amarachi ikwuagwu',
 'Benedette Adewale',
 'Bertholin Pierre',
 'Carlos Jaramillo',
 'Carmen I. Carrión, PsyD',
 'Charlie Corredor',
 'Charren C. Cabaroy',
 'Christian Paylor-Smith',
 'Christian Paylor-Smith',
 'Christina M. Cuttitta',
 'Cliff Bishop',
 'Clyde Lewis',
 'Dana Warmsley, Ph.D.',
 'Evelyn Teran',
 'Fouad Nasraddine',
 'Francis S.',
 'Françoise S.',
 'Grace P. Malonga',
 'Hassan M Oubei',
 'Jason Mighty',
 'Dinely Colon',
 'Elana Cooper',
 'Emmanuel Ekwedike, Ph.D.',
 'Erica F.',
 'Eva Atia',
 'Jean-pierre N Njante',
 'Jesse John, PhD',
 'Jesse St. John',
 'JoAnn Caban',
 'Jose Cortes, MCSD',
 'Jose Perez',
 'Jose Perez',
 'Jose Saltos',
 'Kareem Joshua',
 'Mamadou Moustapha',
 'Maria M.',
 'Mark Carpenay',
 'Mark Carpenay',
 'Michael Tavarez, Ph.D.',
 'Miguel Garcia',
 'Miguel A. Garcia, PhD',
 'Richard Able',
 'Samsiya Ona',
 'Sandra Tinta',
 'Silmilly Toribio Alvarez',
 'Thierno souleymane Diallo',
 'Souleymane Diallo B.S',
 'Thierno Souleymane Diallo',
 'Vadim Acosta',
 'Wahiba Berkane']